#!/bin/sh
#
# Frequency
# Poll every 45 minutes. Change to higher freuqency if you have high nubmber of ESXi Servers
# OR high number of Virtual Machines.
#
# Install:
# cp poll_esx_inventory /usr/local/bin/
#
# Usage:
#  crontab -e
#  45 * * * * /usr/local/bin/poll_esx_inventory
#
# See Wiki for more info
# http://wiki.opendcim.org/wiki/index.php/BackgroundJobs

OPENDCIM='/opt/openDCIM/opendcim'

cd $OPENDCIM
/usr/bin/php poll_esx_inventory.php
